In [1]:
#importing the numpy library
import numpy as np
np.__version__

'1.18.4'

In [2]:
#creating 1D array
a=np.array([1,2,3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [3]:
#creating 2D array
a=np.array([(1,2,3),(4,5,6)])
print(a)
print(a.ndim)
print(a.shape)

[[1 2 3]
 [4 5 6]]
2
(2, 3)


In [4]:
#wrong array--unequal number of columns for each row
a= np.array([(1,2,3,4),(4,5,6)])
print(a)
print(a.ndim)

[(1, 2, 3, 4) (4, 5, 6)]
1


In [5]:
#ones() to create an array of all elements as 1
a,b=np.ones((2,3,4))
print(a)
print()
print(b)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [6]:
#zeros() to create an array of all elements as 0
a,b=np.zeros((2,3,4),dtype=np.int)
print(a)
print()
print(b)


[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [7]:
#full() to create an array of all elements with value specified
c,d=np.full((2,2,2),5.6)
print(c)
#print()
print(d)

[[5.6 5.6]
 [5.6 5.6]]
[[5.6 5.6]
 [5.6 5.6]]


In [8]:
#identity() to create an identity matrix
a=np.identity(3,dtype=np.int)
print(a)



[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [9]:
#creating arrays from random numbers
a=np.random.random((5,2))
print(a)

a=np.random.random_integers(50,100,(3,4))
print(a)


[[0.02992158 0.31362989]
 [0.019723   0.02222008]
 [0.39620265 0.91736663]
 [0.78614697 0.48332943]
 [0.74744906 0.16448555]]
[[90 66 70 80]
 [78 88 59 90]
 [73 68 66 58]]


C:\Users\Nikita Tandel\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: DeprecationWarning: This function is deprecated. Please call randint(50, 100 + 1) instead
  """


In [10]:
#attributes to describe the array
a=np.array([(1,2,3,4),(4,5,6,7)])
print(a)
print(a.size)
print(a.shape)

[[1 2 3 4]
 [4 5 6 7]]
8
(2, 4)


In [11]:
#resizing and reshaping the array
a=np.resize(a,(6,3))
print(a)
a=np.reshape(a,(2,9))
print(a)


[[1 2 3]
 [4 4 5]
 [6 7 1]
 [2 3 4]
 [4 5 6]
 [7 1 2]]
[[1 2 3 4 4 5 6 7 1]
 [2 3 4 4 5 6 7 1 2]]


In [12]:
#indexing and slicing
a=np.array([(1,2,3,4),(3,4,5,6),(8,9,10,11)])

print(a)

print(a[0,2])
print(a[:,2])
print()
print(a[0:2,])


[[ 1  2  3  4]
 [ 3  4  5  6]
 [ 8  9 10 11]]
3
[ 3  5 10]

[[1 2 3 4]
 [3 4 5 6]]


In [13]:
#creating arrays by populating elements on the basis of range
a=np.linspace(1,10,5)
print(a)

a=np.arange(0,25,5)
print(a)



[ 1.    3.25  5.5   7.75 10.  ]
[ 0  5 10 15 20]


In [14]:
#aggregate functions
a=np.array([(8,9),(10,11),(12,13)])
print(len(a))
print(a.min())
print(a.max())
print(a.sum())
print(a.sum()/a.size)
print(a.mean())

3
8
13
63
10.5
10.5


In [15]:
#math functions

a=np.array([(1,0,3),(3,4,5)])

print(np.sqrt(a))
print(np.std(a))
print(np.log(a))
b=np.sqrt(a)
print(b.round(2))

[[1.         0.         1.73205081]
 [1.73205081 2.         2.23606798]]
1.699673171197595
[[0.               -inf 1.09861229]
 [1.09861229 1.38629436 1.60943791]]
[[1.   0.   1.73]
 [1.73 2.   2.24]]


C:\Users\Nikita Tandel\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: RuntimeWarning: divide by zero encountered in log
  import sys


In [16]:
#array operations

x= np.array([(1,2),(3,4)])
y= np.array([(5,6),(3,4)])
print(x)
print(y)
print(x+y)
print(x-y)
print(x*y)
print(x/y)
print(x%y)
print(x@y)
#print(np.dot(x,y))
#print(np.add(x,y))


#np.add(), np.subtract(), np.multiply(), np.divide(), np.remainder()

[[1 2]
 [3 4]]
[[5 6]
 [3 4]]
[[6 8]
 [6 8]]
[[-4 -4]
 [ 0  0]]
[[ 5 12]
 [ 9 16]]
[[0.2        0.33333333]
 [1.         1.        ]]
[[1 2]
 [0 0]]
[[11 14]
 [27 34]]


In [17]:
#help
?np.mean
#print(np.lookfor("mean"))
#help(np.zeros)

In [18]:
#joining/stacking arrays

#print(x)
#print(y)
print()
d=np.concatenate((x,y),axis=0)
print(d)
print()

print(np.vstack((x,y)))

print(np.hstack((x,y)))


[[1 2]
 [3 4]
 [5 6]
 [3 4]]

[[1 2]
 [3 4]
 [5 6]
 [3 4]]
[[1 2 5 6]
 [3 4 3 4]]


In [19]:
#converting array into single row
print(x)
z=x.ravel()
print(z)
print(z.reshape(2,2))

[[1 2]
 [3 4]]
[1 2 3 4]
[[1 2]
 [3 4]]


In [20]:
#adding new elements
x= np.array([(1,2,3),(3,4,5)])
y= np.array([(6,7),(9,10)])
new_array = np.append(x,y)
print(new_array)
new_array=np.reshape(new_array,(5,2))
print(new_array)


[ 1  2  3  3  4  5  6  7  9 10]
[[ 1  2]
 [ 3  3]
 [ 4  5]
 [ 6  7]
 [ 9 10]]


In [21]:
#adding elements in between
x= np.array([(1,2,3),(3,4,5)])
new_array=np.insert(x,[1,3,5],[5,10,15])
print(new_array)

#[1,2,3,3,4,5]

[ 1  5  2  3 10  3  4 15  5]


In [22]:
#deleting elements from the array
new_array=np.delete(new_array,[1,2])
print(new_array)

[ 1  3 10  3  4 15  5]


In [23]:
#updating array elements
x= np.array([(1,2,3),(3,4,5)])
x[0,1]=7

In [24]:
print(x)

[[1 7 3]
 [3 4 5]]


In [25]:
#creating array by reading data from file
my_array2 = np.genfromtxt(r'C:\Users\Nikita Tandel\mypython\niks\niks\arraydata.txt',
                          skip_header=1,delimiter=",",filling_values=0,
                          unpack=False,dtype=np.int)
print(my_array2)

[[1 2 3]
 [4 0 6]
 [7 8 9]]
